"""Fixed Recursion Error

Revision ID: 446a87b75c13
Revises: e2fcb89d58b3
Create Date: 2023-04-07 20:22:46.876059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446a87b75c13'
down_revision = 'e2fcb89d58b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_index('ix_restaurants_name')
        batch_op.create_index(batch_op.f('ix_restaurants_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurants_name'))
        batch_op.create_index('ix_restaurants_name', ['name'], unique=False)

    # ### end Alembic commands ###
