"""Added joiner table

Revision ID: bb114bb05244
Revises: 9edae9de704a
Create Date: 2023-04-23 20:05:48.220065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb114bb05244'
down_revision = '9edae9de704a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_item_allergies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=True),
    sa.Column('allergy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['allergy_id'], ['allergies.id'], name=op.f('fk_menu_item_allergies_allergy_id_allergies')),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_menu_item_allergies_menu_item_id_menu_items')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_allergies_menu_item_id_menu_items', type_='foreignkey')
        batch_op.drop_column('menu_item_id')

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_index('ix_menu_items_restaurant_id')
        batch_op.create_index(batch_op.f('ix_menu_items_restaurant_id'), ['restaurant_id'], unique=False)

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_index('ix_restaurants_name')
        batch_op.create_index(batch_op.f('ix_restaurants_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurants_name'))
        batch_op.create_index('ix_restaurants_name', ['name'], unique=False)

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_items_restaurant_id'))
        batch_op.create_index('ix_menu_items_restaurant_id', ['restaurant_id'], unique=False)

    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_allergies_menu_item_id_menu_items', 'menu_items', ['menu_item_id'], ['id'])

    op.drop_table('menu_item_allergies')
    # ### end Alembic commands ###
